#pragma once

#define CORES 16
#define STACK_SIZE 32
#define GLOBALS 128
#define MAX_LABELS 128
#define SAMPLERS 4
#define MAX_SAMPLER_SIZE_BITS 16
#define MAX_SAMPLER_SIZE (1 << MAX_SAMPLER_SIZE_BITS)
#define MAX_SAMPLER_SIZE_MASK (MAX_SAMPLER_SIZE - 1)
#define MAX_PROGRAM_LENGTH 16384
#define MAX_NAME_LENGTH 32
#define MAX_HANDLERS 16
#define MAX_FORWARDS MAX_LABELS
#define MAX_ERROR_DESC_LENGTH 128
